In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('/content/test.csv')
display(df.head())

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied

In [3]:
print('Checking for missing values:')
missing_values = df.isnull().sum()
print(missing_values[missing_values > 0])

Checking for missing values:
Arrival Delay in Minutes    83
dtype: int64

In [4]:
print('Missing values for all columns (descending order):')
print(missing_values.sort_values(ascending=False))

Missing values for all columns (descending order):
Arrival Delay in Minutes             83
id                                    0
Gender                                0
Customer Type                         0
Age                                   0
Type of Travel                        0
Class                                 0
Flight Distance                       0
Unnamed: 0                            0
Inflight wifi service                 0
Departure/Arrival time convenient     0
Gate location                         0
Ease of Online booking                0
Online boarding                       0
Seat comfort                          0
Inflight entertainment                0
Food and drink                        0
On-board service                      0
Leg room service                      0
Checkin service                       0
Baggage handling                      0
Inflight service                      0
Cleanliness                           0
Departure Delay in Minutes            0
satisfaction                          0
dtype: int64

In [5]:
print('Missing values for all columns (descending order, as percentage):')
missing_values_percent = (df.isnull().sum() / len(df)) * 100
print(missing_values_percent[missing_values_percent > 0].sort_values(ascending=False))

Missing values for all columns (descending order, as percentage):
Arrival Delay in Minutes    0.319526
dtype: float64

In [7]:
median_arrival_delay = df['Arrival Delay in Minutes'].median()
print(f"Median of 'Arrival Delay in Minutes': {median_arrival_delay}")
df['Arrival Delay in Minutes'] = df['Arrival Delay in Minutes'].fillna(median_arrival_delay)

print('\nChecking for missing values after imputation:')
missing_values_after_imputation = df['Arrival Delay in Minutes'].isnull().sum()
print(f"Missing values in 'Arrival Delay in Minutes': {missing_values_after_imputation}")

display(df.head())

Median of 'Arrival Delay in Minutes': 0.0

Checking for missing values after imputation:
Missing values in 'Arrival Delay in Minutes': 0

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,Female,Loyal Customer,52,Business travel,Eco,160,5,4,...,5,5,5,5,2,5,5,50,44.0,satisfied
1,1,90035,Female,Loyal Customer,36,Business travel,Business,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,satisfied
2,2,12360,Male,disloyal Customer,20,Business travel,Eco,192,2,0,...,2,4,1,3,2,2,2,0,0.0,neutral or dissatisfied
3,3,77959,Male,Loyal Customer,44,Business travel,Business,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,satisfied
4,4,36875,Female,Loyal Customer,49,Business travel,Eco,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,satisfied

In [8]:
print('Identificando colunas com tipo string (object) e seus valores únicos:')
for column in df.select_dtypes(include='object').columns:
    print(f"\nColuna: {column}")
    print(df[column].unique())

Identificando colunas com tipo string (object) e seus valores únicos:

Coluna: Gender
['Female' 'Male']

Coluna: Customer Type
['Loyal Customer' 'disloyal Customer']

Coluna: Type of Travel
['Business travel' 'Personal Travel']

Coluna: Class
['Eco' 'Business' 'Eco Plus']

Coluna: satisfaction
['satisfied' 'neutral or dissatisfied']

In [9]:
gender_mapping = {'Male': 0, 'Female': 1}
df['Gender'] = df['Gender'].map(gender_mapping)

customer_type_mapping = {'disloyal Customer': 0, 'Loyal Customer': 1}
df['Customer Type'] = df['Customer Type'].map(customer_type_mapping)

type_of_travel_mapping = {'Personal Travel': 0, 'Business travel': 1}
df['Type of Travel'] = df['Type of Travel'].map(type_of_travel_mapping)

class_mapping = {'Eco': 0, 'Eco Plus': 1, 'Business': 2}
df['Class'] = df['Class'].map(class_mapping)

satisfaction_mapping = {'neutral or dissatisfied': 0, 'satisfied': 1}
df['satisfaction'] = df['satisfaction'].map(satisfaction_mapping)

print('DataFrame após a transformação das colunas categóricas:')
display(df.head())

DataFrame após a transformação das colunas categóricas:

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,19556,1,1,52,1,0,160,5,4,...,5,5,5,5,2,5,5,50,44.0,1
1,1,90035,1,1,36,1,2,2863,1,1,...,4,4,4,4,3,4,5,0,0.0,1
2,2,12360,0,0,20,1,0,192,2,0,...,2,4,1,3,2,2,2,0,0.0,0
3,3,77959,0,1,44,1,2,3377,0,0,...,1,1,1,1,3,1,4,0,6.0,1
4,4,36875,1,1,49,1,0,1182,2,3,...,2,2,2,2,4,2,4,0,20.0,1

In [10]:
# Removendo colunas 'id' e 'Unnamed: 0'
df = df.drop(['id', 'Unnamed: 0'], axis=1)

# Identificando colunas numéricas (incluindo as que foram mapeadas de categóricas)
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()

# Garantindo que a coluna alvo 'satisfaction' esteja incluída e que outras colunas categóricas (agora numéricas) também sejam mantidas
# Excluir 'satisfaction' da lista de colunas numéricas para adicioná-la explicitamente depois, se já não estiver lá
if 'satisfaction' in numerical_cols:
    numerical_cols.remove('satisfaction')

# Definindo as colunas finais a serem mantidas
# Inclui todas as colunas que já são numéricas (excluindo 'satisfaction' temporariamente)
# e adiciona 'satisfaction' no final, garantindo que ela esteja presente.
final_columns = [col for col in numerical_cols if col != 'satisfaction'] + ['satisfaction']

# Removendo quaisquer duplicatas (caso 'satisfaction' já estivesse na lista original e foi adicionada novamente)
final_columns = list(dict.fromkeys(final_columns))

df = df[final_columns]

print('Colunas restantes no DataFrame:')
print(df.columns.tolist())
display(df.head())

Colunas restantes no DataFrame:
['Gender', 'Customer Type', 'Age', 'Type of Travel', 'Class', 'Flight Distance', 'Inflight wifi service', 'Departure/Arrival time convenient', 'Ease of Online booking', 'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort', 'Inflight entertainment', 'On-board service', 'Leg room service', 'Baggage handling', 'Checkin service', 'Inflight service', 'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes', 'satisfaction']

,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,Ease of Online booking,Gate location,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,1,1,52,1,0,160,5,4,3,4,...,5,5,5,5,2,5,5,50,44.0,1
1,1,1,36,1,2,2863,1,1,3,1,...,4,4,4,4,3,4,5,0,0.0,1
2,0,0,20,1,0,192,2,0,2,4,...,2,4,1,3,2,2,2,0,0.0,0
3,0,1,44,1,2,3377,0,0,0,2,...,1,1,1,1,3,1,4,0,6.0,1
4,1,1,49,1,0,1182,2,3,4,3,...,2,2,2,2,4,2,4,0,20.0,1

In [11]:
from sklearn.model_selection import train_test_split

# Definindo as features (X) e a variável alvo (y)
X = df.drop('satisfaction', axis=1)
y = df['satisfaction']

# Dividindo os dados em conjuntos de treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print('Tamanho dos conjuntos de treino e teste:')
print(f'X_train: {X_train.shape}')
print(f'X_test: {X_test.shape}')
print(f'y_train: {y_train.shape}')
print(f'y_test: {y_test.shape}')

Tamanho dos conjuntos de treino e teste:
X_train: (20780, 22)
X_test: (5196, 22)
y_train: (20780,)
y_test: (5196,)

### Treinamento do Modelo RandomForestClassifier

In [12]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

# Inicializando o modelo RandomForestClassifier
model = RandomForestClassifier(n_estimators=100, random_state=42)

# Treinando o modelo com os dados de treino
model.fit(X_train, y_train)

print('Modelo RandomForestClassifier treinado com sucesso!')

Modelo RandomForestClassifier treinado com sucesso!

### Avaliação do Modelo

In [13]:
# Fazendo predições no conjunto de teste
y_pred = model.predict(X_test)

# Calculando a acurácia do modelo
acuracia = accuracy_score(y_test, y_pred)
print(f'Acurácia do modelo RandomForestClassifier: {acuracia:.4f}')

Acurácia do modelo RandomForestClassifier: 0.9511

### Salvando e Carregando o Modelo, e Simulação de Predição

In [14]:
import joblib
import pandas as pd

# 1. Salvar o modelo treinado
filename = 'modelo_airline.pkl'
joblib.dump(model, filename)
print(f'Modelo salvo como {filename}')

# 2. Carregar o modelo salvo
loaded_model = joblib.load(filename)
print(f'Modelo carregado de {filename}')

# 3. Simular uma predição para um passageiro fictício
# Recuperar mapeamentos e a ordem das colunas usadas no treino
# gender_mapping = {'Male': 0, 'Female': 1}
# customer_type_mapping = {'disloyal Customer': 0, 'Loyal Customer': 1}
# type_of_travel_mapping = {'Personal Travel': 0, 'Business travel': 1}
# class_mapping = {'Eco': 0, 'Eco Plus': 1, 'Business': 2}
# satisfaction_mapping = {'neutral or dissatisfied': 0, 'satisfied': 1}

# Inverter o satisfaction_mapping para exibir o resultado
reverse_satisfaction_mapping = {v: k for k, v in satisfaction_mapping.items()}

# Criar dados do passageiro fictício
# Características específicas do passageiro:
fictitious_passenger_data = {
    'Gender': gender_mapping['Male'], # homem
    'Customer Type': customer_type_mapping['Loyal Customer'], # cliente leal
    'Age': X_train['Age'].median(), # Usar mediana para idade
    'Type of Travel': type_of_travel_mapping['Business travel'], # viagem a trabalho
    'Class': class_mapping['Business'], # classe Business
}

# Preencher as demais colunas com as medianas de X_train
for col in X_train.columns:
    if col not in fictitious_passenger_data:
        fictitious_passenger_data[col] = X_train[col].median()

# Criar um DataFrame a partir dos dados do passageiro, garantindo a ordem das colunas
fictitious_df = pd.DataFrame([fictitious_passenger_data], columns=X_train.columns)

# Fazer a predição
prediction = loaded_model.predict(fictitious_df)[0]

# Mostrar o resultado
result_text = reverse_satisfaction_mapping[prediction]
print(f'A predição para o passageiro fictício é: {result_text.upper()}')

Modelo salvo como modelo_airline.pkl
Modelo carregado de modelo_airline.pkl
A predição para o passageiro fictício é: SATISFIED